development:
  adapter: postgresql
  database: tic_tac_toe_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: tic_tac_toe_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tic_tac_toe_production
  pool: 5
  timeout: 5000
  username: hkviiumopmnxty
  password: